server:
  port: 8123
  servlet:
    context-path: /api

myapi:
  client:
    access-key: ak
    secret-key: sk

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


